### PR TITLE
Clone the branch that is being pushed

### PR DESCRIPTION
**Pull request by droidlabour**
eae8873
`Earlier behaviour:` It's always cloning `master` branch
`Expected behaviour:` Clone the branch where commits are actually being pushed to

685bba9
`Earlier behaviour:` Github integration was missing and zip contains dir prefix
`Expected behaviour:` Added Github integration and create zip without any dir prefix

### CODE REVIEW

**Comment by santiagocardenas** [comment]
Thank you for the contribution @droidlabour 
Please confirm that this contribution is under the terms of the Apache 2.0 license.

**Comment by droidlabour** [comment]
@santiagocardenas Yeah it's under Apache 2.0 license.

**Review by jaymccon — CHANGES_REQUESTED** [review]
Thanks for the contribution @droidlabour.

I see you've included some broad style changes in your commits, while this is appreciated (the original style was far from pep8) it does make the intent and functionality of the commits harder to read. 

I have done a commit https://github.com/aws-quickstart/quickstart-git2s3/commit/11077c0a9b545f277f7adaf23db5ac2bfad6c6d2 to get the style mostly fixed. 

Sorry for being pedantic, but can you please refactor your pr so that it only makes functional changes from the latest commit level in the develop branch.

**Comment by droidlabour** [comment]
@jaymccon I've added the changes although I've decided to stick with PEP8 standards for comments and some long expressions.

**Pull request merged**
