### PR TITLE
updated the ZipDl to support TFS as a source, created a new zip, adde…

### PR DESCRIPTION
**Pull request by developertofu**
…d a comment to the GitPullS3 lambda to add the SSH option in the future

### CODE REVIEW

**Comment by santiagocardenas** [comment]
@jaymccon please take a look at this.

**Comment by santiagocardenas** [comment]
@developertofu please remove the .DS_Store file.

**Comment by developertofu** [comment]
Done

**Comment by jaymccon** [comment]
Looks good to me :)

**Pull request merged**
